// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneZero.Entity.DatabaseContext.SqlContext;

namespace OneZero.Api.Migrations
{
    [DbContext(typeof(MSSqlContext))]
    [Migration("20181229213537_init-1")]
    partial class init1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OneZero.Entity.Identity.ModulePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDelete");

                    b.Property<Guid>("ModuleId");

                    b.Property<Guid>("PermissionId");

                    b.Property<int>("SeqNo");

                    b.Property<Guid>("TenanId");

                    b.HasKey("Id");

                    b.HasIndex("SeqNo");

                    b.HasIndex("PermissionId", "ModuleId");

                    b.ToTable("TModulePermission");
                });

            modelBuilder.Entity("OneZero.Entity.Identity.ModuleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("IsDelete");

                    b.Property<Guid?>("ModuleTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("ParentId");

                    b.Property<Guid?>("RoleId");

                    b.Property<Guid>("TenanId");

                    b.HasKey("Id");

                    b.HasIndex("ModuleTypeId");

                    b.HasIndex("Name");

                    b.HasIndex("RoleId");

                    b.ToTable("TModuleType");
                });

            modelBuilder.Entity("OneZero.Entity.Identity.PermissionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("IsDelete");

                    b.Property<Guid?>("ModuleTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Remark")
                        .HasMaxLength(50);

                    b.Property<int>("RowNo");

                    b.Property<Guid>("TenanId");

                    b.HasKey("Id");

                    b.HasIndex("ModuleTypeId");

                    b.HasIndex("Name");

                    b.ToTable("TPermissionType");
                });

            modelBuilder.Entity("OneZero.Entity.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<bool>("IsDelete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Remark")
                        .HasMaxLength(2000);

                    b.Property<Guid>("TenanId");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.ToTable("TRole");
                });

            modelBuilder.Entity("OneZero.Entity.Identity.RoleModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDelete");

                    b.Property<Guid>("ModleId");

                    b.Property<int>("PermissionValue");

                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("TenanId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "ModleId");

                    b.ToTable("TRoleModule");
                });

            modelBuilder.Entity("OneZero.Entity.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("IsDelete");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset>("LockoutEnd");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("PhoneConfirmed");

                    b.Property<Guid>("TenanId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("TUser");
                });

            modelBuilder.Entity("OneZero.Entity.Identity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDelete");

                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("TenanId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "UserId");

                    b.ToTable("TUserRole");
                });

            modelBuilder.Entity("OneZero.Entity.Identity.ModuleType", b =>
                {
                    b.HasOne("OneZero.Entity.Identity.ModuleType")
                        .WithMany("SubMouldes")
                        .HasForeignKey("ModuleTypeId");

                    b.HasOne("OneZero.Entity.Identity.Role")
                        .WithMany("Modules")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("OneZero.Entity.Identity.PermissionType", b =>
                {
                    b.HasOne("OneZero.Entity.Identity.ModuleType")
                        .WithMany("Permissions")
                        .HasForeignKey("ModuleTypeId");
                });

            modelBuilder.Entity("OneZero.Entity.Identity.Role", b =>
                {
                    b.HasOne("OneZero.Entity.Identity.User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
