// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneZero.EntityFrameworkCore;

namespace SouthStar.VehSch.Api.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20190403151425_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OneZero.Core.Models.Permissions.ModuleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("IsDelete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid?>("ParentId");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<Guid>("TenanId");

                    b.HasKey("Id");

                    b.HasIndex("Name", "IsDelete", "TenanId")
                        .IsUnique();

                    b.ToTable("TModuleType");
                });

            modelBuilder.Entity("OneZero.Core.Models.Permissions.PermissionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApiPath")
                        .HasMaxLength(50);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("IsDelete");

                    b.Property<Guid>("ModuleId")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Remark")
                        .HasMaxLength(50);

                    b.Property<int>("RowNo");

                    b.Property<Guid>("TenanId");

                    b.HasKey("Id");

                    b.HasIndex("Name", "IsDelete", "TenanId")
                        .IsUnique();

                    b.ToTable("TPermissionType");
                });

            modelBuilder.Entity("OneZero.Core.Models.Permissions.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<Guid>("IsDelete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Remark")
                        .HasMaxLength(2000);

                    b.Property<Guid>("TenanId");

                    b.HasKey("Id");

                    b.HasIndex("Name", "IsDelete", "TenanId")
                        .IsUnique();

                    b.ToTable("TRole");
                });

            modelBuilder.Entity("OneZero.Core.Models.Permissions.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<Guid>("IsDelete");

                    b.Property<bool>("LockoutEnabled")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("LockoutEnd");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("PhoneConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<Guid>("TenanId");

                    b.HasKey("Id");

                    b.HasIndex("Account", "IsDelete", "TenanId")
                        .IsUnique();

                    b.ToTable("TUser");
                });

            modelBuilder.Entity("SouthStar.VehSch.Core.ApplicationFlow.Models.CheckContents", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ApplyId");

                    b.Property<string>("ApplyNum")
                        .HasMaxLength(50);

                    b.Property<int>("ApplyType");

                    b.Property<string>("CheckReply")
                        .HasMaxLength(500);

                    b.Property<int>("CheckStatus");

                    b.Property<Guid>("CheckUserId");

                    b.Property<string>("CheckUserName")
                        .HasMaxLength(30);

                    b.Property<DateTime>("CreateDate");

                    b.Property<Guid>("IsDelete");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<Guid>("TenanId");

                    b.HasKey("Id");

                    b.HasIndex("ApplyNum", "IsDelete", "TenanId")
                        .IsUnique()
                        .HasFilter("[ApplyNum] IS NOT NULL");

                    b.ToTable("TCheckContents");
                });

            modelBuilder.Entity("SouthStar.VehSch.Core.ApplicationFlow.Models.VehicleApplications", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ApplicantId");

                    b.Property<string>("ApplicantName")
                        .HasMaxLength(100);

                    b.Property<string>("ApplicantPhone")
                        .HasMaxLength(30);

                    b.Property<string>("ApplyNum")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ApplyReson")
                        .HasMaxLength(500);

                    b.Property<DateTime>("BackPlanTime");

                    b.Property<int>("CarProperty");

                    b.Property<string>("CarType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreateDate");

                    b.Property<Guid>("DepartmentId");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(500);

                    b.Property<string>("Destination")
                        .HasMaxLength(200);

                    b.Property<string>("FileName")
                        .HasMaxLength(2000);

                    b.Property<Guid>("IsDelete");

                    b.Property<Guid>("ReciverId");

                    b.Property<string>("ReciverMobile")
                        .HasMaxLength(50);

                    b.Property<string>("Remark")
                        .HasMaxLength(500);

                    b.Property<DateTime>("StartPlanTime");

                    b.Property<string>("StartPoint")
                        .HasMaxLength(200);

                    b.Property<int>("Status");

                    b.Property<Guid>("TenanId");

                    b.Property<string>("UseArea")
                        .HasMaxLength(100);

                    b.Property<string>("UserCount")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("UserMobile")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .HasMaxLength(50);

                    b.Property<string>("UserTitle")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ApplyNum", "IsDelete", "TenanId")
                        .IsUnique();

                    b.ToTable("TVehicleApplications");
                });

            modelBuilder.Entity("SouthStar.VehSch.Core.Dispatch.Models.DispatchFees", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("DispatchId");

                    b.Property<float>("EndMiles");

                    b.Property<float>("EtcFee");

                    b.Property<float>("HighSpeedFee");

                    b.Property<Guid>("IsDelete");

                    b.Property<float>("OilFee");

                    b.Property<float>("ParkFee");

                    b.Property<float>("StartMiles");

                    b.Property<Guid>("TenanId");

                    b.Property<float>("TotalPrice");

                    b.Property<float>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("DispatchId", "TenanId", "IsDelete")
                        .IsUnique();

                    b.ToTable("TDispatchFees");
                });

            modelBuilder.Entity("SouthStar.VehSch.Core.Dispatch.Models.VehicleDispatchs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicantName");

                    b.Property<string>("ApplicantPhone");

                    b.Property<DateTime>("ApplyDate");

                    b.Property<Guid>("ApplyId");

                    b.Property<string>("ApplyNum")
                        .HasMaxLength(100);

                    b.Property<string>("ApplyReson")
                        .HasMaxLength(500);

                    b.Property<DateTime>("BackPlanTime");

                    b.Property<int>("CarProperty");

                    b.Property<string>("CarType")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Destination")
                        .HasMaxLength(200);

                    b.Property<int>("DispatchType");

                    b.Property<Guid>("DriverId");

                    b.Property<string>("DriverName");

                    b.Property<string>("DriverPhone");

                    b.Property<Guid>("IsDelete");

                    b.Property<string>("PlateNumber");

                    b.Property<int>("QueueNo");

                    b.Property<DateTime>("StartPlanTime");

                    b.Property<string>("StartPoint")
                        .HasMaxLength(200);

                    b.Property<Guid>("TenanId");

                    b.Property<string>("UserCount");

                    b.Property<string>("UserDepartment");

                    b.Property<string>("UserMobile");

                    b.Property<string>("UserName");

                    b.Property<string>("UserTitle");

                    b.Property<Guid>("VehcileId");

                    b.HasKey("Id");

                    b.HasIndex("ApplyNum", "TenanId", "IsDelete")
                        .IsUnique()
                        .HasFilter("[ApplyNum] IS NOT NULL");

                    b.ToTable("TVehicleDispatchs");
                });

            modelBuilder.Entity("SouthStar.VehSch.Core.Setting.Models.Departments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("IsDelete");

                    b.Property<Guid>("ParentDepartmentId");

                    b.Property<string>("Remark")
                        .HasMaxLength(500);

                    b.Property<int>("RowNo");

                    b.Property<Guid>("TenanId");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentName", "TenanId", "IsDelete")
                        .IsUnique();

                    b.ToTable("TDepartments");
                });

            modelBuilder.Entity("SouthStar.VehSch.Core.Setting.Models.Drivers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(100);

                    b.Property<int>("Age");

                    b.Property<Guid>("DepartmentId");

                    b.Property<string>("DrivingLicNum")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<string>("Image")
                        .HasMaxLength(2000);

                    b.Property<Guid>("IsDelete");

                    b.Property<DateTime>("IssueDate");

                    b.Property<string>("MobileNum")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PermittedType")
                        .HasMaxLength(30);

                    b.Property<string>("PhoneNum")
                        .HasMaxLength(20);

                    b.Property<string>("Remark")
                        .HasMaxLength(500);

                    b.Property<int>("Sex");

                    b.Property<int>("Status")
                        .HasMaxLength(10);

                    b.Property<Guid>("TenanId");

                    b.HasKey("Id");

                    b.HasIndex("DrivingLicNum", "IsDelete", "TenanId")
                        .IsUnique();

                    b.HasIndex("PhoneNum", "IsDelete", "TenanId")
                        .IsUnique()
                        .HasFilter("[PhoneNum] IS NOT NULL");

                    b.ToTable("TDrivers");
                });

            modelBuilder.Entity("SouthStar.VehSch.Core.Setting.Models.Vehicles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApprovedSeating");

                    b.Property<string>("BookOriginValue")
                        .HasMaxLength(20);

                    b.Property<string>("CarIcon")
                        .HasMaxLength(100);

                    b.Property<string>("CurbWeight")
                        .HasMaxLength(20);

                    b.Property<int>("CurrentState")
                        .HasMaxLength(50);

                    b.Property<Guid>("DepartmentId");

                    b.Property<string>("Displacament")
                        .HasMaxLength(20);

                    b.Property<Guid>("DriverId");

                    b.Property<string>("EngineNo")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("FACardNum")
                        .HasMaxLength(20);

                    b.Property<string>("Image")
                        .HasMaxLength(2000);

                    b.Property<int>("InitMileage");

                    b.Property<Guid>("IsDelete");

                    b.Property<string>("LoadWeight")
                        .HasMaxLength(20);

                    b.Property<int>("OilType")
                        .HasMaxLength(20);

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("PurchasePrice");

                    b.Property<string>("Remark")
                        .HasMaxLength(500);

                    b.Property<int>("TankCapacity");

                    b.Property<Guid>("TenanId");

                    b.Property<string>("TerminalNo")
                        .HasMaxLength(30);

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("VechileType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("VehicleBrand")
                        .HasMaxLength(50);

                    b.Property<string>("VehicleColor")
                        .HasMaxLength(20);

                    b.Property<string>("VehicleLicOwner")
                        .HasMaxLength(30);

                    b.Property<int>("VehicleProperties");

                    b.HasKey("Id");

                    b.HasIndex("EngineNo", "IsDelete", "TenanId")
                        .IsUnique();

                    b.HasIndex("PlateNumber", "IsDelete", "TenanId")
                        .IsUnique();

                    b.HasIndex("VIN", "IsDelete", "TenanId")
                        .IsUnique();

                    b.ToTable("TVehicles");
                });

            modelBuilder.Entity("OneZero.Core.Models.Permissions.Role", b =>
                {
                    b.OwnsMany("OneZero.Core.Models.Permissions.RoleModule", "RoleModules", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("IsDelete");

                            b1.Property<Guid>("ModuleId");

                            b1.Property<Guid>("RoleId");

                            b1.Property<int>("RowNo");

                            b1.Property<Guid>("TenanId");

                            b1.HasKey("Id");

                            b1.HasIndex("RoleId", "ModuleId", "TenanId")
                                .IsUnique();

                            b1.ToTable("TRoleModule");

                            b1.HasOne("OneZero.Core.Models.Permissions.Role")
                                .WithMany("RoleModules")
                                .HasForeignKey("RoleId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsMany("OneZero.Core.Models.Permissions.RolePermission", "RolePermission", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("IsDelete");

                            b1.Property<Guid>("ModuleId");

                            b1.Property<Guid>("PermissionId");

                            b1.Property<Guid>("RoleId");

                            b1.Property<int>("SeqNo");

                            b1.Property<Guid>("TenanId");

                            b1.HasKey("Id");

                            b1.HasIndex("RoleId");

                            b1.HasIndex("SeqNo");

                            b1.HasIndex("PermissionId", "RoleId", "TenanId")
                                .IsUnique();

                            b1.ToTable("TRolePermission");

                            b1.HasOne("OneZero.Core.Models.Permissions.Role")
                                .WithMany("RolePermission")
                                .HasForeignKey("RoleId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("OneZero.Core.Models.Permissions.User", b =>
                {
                    b.OwnsMany("OneZero.Core.Models.Permissions.UserRole", "UserRoles", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("IsDelete");

                            b1.Property<Guid>("RoleId");

                            b1.Property<int>("RowNo");

                            b1.Property<Guid>("TenanId");

                            b1.Property<Guid>("UserId");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.HasIndex("RoleId", "UserId", "TenanId");

                            b1.ToTable("TUserRole");

                            b1.HasOne("OneZero.Core.Models.Permissions.User")
                                .WithMany("UserRoles")
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
